name: Deploy Flask App with Docker

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: yourdockerhubusername/yourimage:latest  # Replace with your Docker Hub repo

      - name: Deploy with Docker Compose (Remote Server)
        run: |
          ssh ADMIN@192.168.100.60 'cd /mnt/c/Users/ADMIN/Desktop/automation001 && docker-compose down && docker-compose up -d'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.FIRSTAUTOMATIONSECRETKEY }}
